title = "00"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = "spindarella"
text = "wow what a wonderful cavern"

[[dialogue]]
name = "spindarella"
text = "I can't wait to use my awesome web marionette skills to create some abominations..."
transition = { AppState = "Game" }
