title = "01"

[[spawn_scene]]
name = "test"
spawn_on_dialogue = 0
despawn_on_dialogue = 6

[[dialogue]]
name = ""
text = ""

[[dialogue]]
name = "spindarella"
text = ",,,pretty,,"

[[dialogue]]
name = "spindarella"
text = "oh gosh I am so sorry hi hello hi"

[[dialogue]]
name = "silkarella"
text = "that's okay darling >x3"

[[dialogue]]
name = "silkarella"
text = "I saw how you monched up those monsters, very nice I must say hehe"

[[dialogue]]
name = "silkarella"
text = "I'm silkarella (they them) by the way, I really must be off now though"

[[dialogue]]
name = "spindarella"
text = "..."

[[dialogue]]
name = "spindarella"
text = "w-w-wait sil- oh.. they're gone"

[[dialogue]]
name = "spindarella"
text = "I didn't even get to tell them my name..."

transition = { AppState = "Game" }
