title = "02"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test3"

[[dialogue]]
name = "spindarella"
text = "I wonder where silkarella is at..."

[[dialogue]]
name = "spindarella"
text = "Ugh stay focused spindy, we've got a job to do"

transition = { AppState = "Game" }
