title = "03"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = "spindarella"
text = "whew that was a big one"

[[dialogue]]
name = "spindarella"
text = "it will make a fine addition to my collection"

[[dialogue]]
name = "silkarella"
text = "oh hey spindy, you're a sight for sore eyes"

[[dialogue]]
name = "spindarella"
text = "silkarella!! tthanks,, hey wait how did you kno-"

[[dialogue]]
name = "silkarella"
text = "good job with that big monster back there by the way, *very* impressive"

[[dialogue]]
name = "silkarella"
text = "be careful around here though, I heard that in the heart of the cavern there's a truly gargantuan specimen"

transition = { AppState = "Game" }
