title = "06"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = "silkarella"
text = "I don't remember why you said you were here spindy"

[[dialogue]]
name = "spindarella"
text = "Whoops, that's 'cos i didn't."

[[dialogue]]
name = "spindarella"
text = "Pure chance really, I wanted a fresh start and just took off in this direction"

[[dialogue]]
name = "silkarella"
text = "And the creating of your little monster army? hehe"

[[dialogue]]
name = "spindarella"
text = "It's like exercise I guess, got to keep using these webs for something or I'll get *rust*y (badumtish)"

[[dialogue]]
name = "silkarella"
text = "Oh..."

transition = { AppState = "Game" }
