title = "07"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = ""
text = ""

[[dialogue]]
name = "spindarella"
text = "What's wrong, you've been kind of off since you asked why I came here"

[[dialogue]]
name = "silkarella"
text = "Oh, there were some people who came here to kill that gargantuan specimen I mentioned earlier."

[[dialogue]]
name = "silkarella"
text = "I thought maybe you were here for the same reason."

[[dialogue]]
name = "spindarella"
text = "wow, no I am not brave enough for that"

[[dialogue]]
name = "silkarella"
text = "well dont worry spindy, i'll protect you if they show up"

[[dialogue]]
name = "spindarella"
text = "my knight in shining armour..."
transition = { AppState = "Game" }
