title = "08"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = ""
text = ""

[[dialogue]]
name = "silkarella"
text = "Well, I think this is far enough in. I'm sorry spindy"

[[dialogue]]
name = "spindarella"
text = "What's going on silky, are you feeling alright?"

[[dialogue]]
name = "silkarella"
text = "We're far enough into the cavern that there is no chance for you to escape, so I can drop the pretense"

[[dialogue]]
name = "silkarella"
text = "That 'gargantuan speciment' I mentioned earlier is actually me, and now I'm going to devour you for food"

[[dialogue]]
name = "spindarella"
text = "Ugh. I was hoping you would give me more time to build up strength but I suppose this will have to do"

[[dialogue]]
name = "silkarella"
text = "w-what"

[[dialogue]]
name = "spindarella"
text = "I wasn't lying earlier when I said it was pure chance I came here, but it wasn't the whole truth."

[[dialogue]]
name = "spindarella"
text = "I ended up here by chance, but I went down this cavern looking to hunt you down after hearing what you'd done."

[[dialogue]]
name = "silkarella"
text = "*transforms into a giant mass of flesh with limbs sticking out*"

transition = { AppState = "Game" }
