title = "10"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = ""
text = ""

[[dialogue]]
name = "spindarella"
text = "... im not going to jinx it"

transition = { AppState = "MainMenu" }
